cookie:
  expiry_days: 30
  key: Roland_is_awesome_and_so_are_you_if_you_read_this
  name: Roland_delicious_cookie
credentials:
  usernames:
    roland:
      email: haller.roland@gmail.com
      name: Roland Haller
      password: $2b$12$sFtSBe/Vc7uUuN3eqYRlJeaZ3/ec3vXpcyylHo3tHsQAq/FqHtoD2
preauthorized:
  emails: []
