cookie:
  expiry_days: 30
  key: Roland_is_awesome_and_so_are_you_if_you_read_this
  name: Roland_delicious_cookie
credentials:
  usernames:
    bugibhub:
      email: bugibhub@gmail.com
      name: bugihbhub
      password: $2b$12$qj5nNGvLEnFMfhVHFOL9HOeJgRFaQ.SGwOsyEP9dkuuam2uMlC1dO
    bugihbub:
      email: bugihbub@gmail.com
      name: bugihbub
      password: $2b$12$n9kSaLCrLtmrS4YdTY3XDO/eUJI8hp.TFW87.uDKpijoV8lwQ7t0q
    haller:
      email: Roland.Haller@tsunagaru.co.jp
      name: haller
      password: $2b$12$8pTC.Z8Sc6hWt2xRIgVykOTfRNNyTWdGYj4Gil919tL74uITIw9di
    roland:
      email: haller.roland@gmail.com
      name: Roland Haller
      password: $2b$12$sFtSBe/Vc7uUuN3eqYRlJeaZ3/ec3vXpcyylHo3tHsQAq/FqHtoD2
preauthorized:
  emails: []
